# Generated by Django 3.2.7 on 2021-09-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Secret')], max_length=1)),
                ('description', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=128)),
                ('linkin', models.CharField(max_length=128)),
                ('facebook', models.CharField(max_length=128)),
                ('instagram', models.CharField(max_length=128)),
                ('github', models.CharField(max_length=128)),
                ('degree', models.CharField(choices=[('B', 'Bachelor'), ('M', 'Master'), ('D', 'Doctor')], max_length=2)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
