# Generated by Django 3.2.7 on 2021-09-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_name_userinfo_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
