# Generated by Django 3.2.7 on 2021-09-25 13:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210925_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='data',
            new_name='date',
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='titleImage',
            field=models.ImageField(blank=True, default='default/note.jpg', null=True, upload_to='note_images/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
