# Generated by Django 3.2.7 on 2021-09-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='good',
        ),
        migrations.AlterField(
            model_name='food',
            name='titleImage',
            field=models.ImageField(blank=True, default='default/food.jpg', null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='titleImage',
            field=models.ImageField(blank=True, default='default/program.jpg', null=True, upload_to='program_images/'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='titleImage',
            field=models.ImageField(blank=True, default='default/travel.jpg', null=True, upload_to='travel_images/'),
        ),
    ]
