# Generated by Django 3.2.7 on 2021-09-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_program_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='good',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='degree',
            field=models.CharField(choices=[('N', 'None'), ('B', 'Bachelor'), ('M', 'Master'), ('D', 'Doctor')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='facebook',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='github',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='instagram',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='linkin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
