# Generated by Django 3.2.7 on 2021-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_userinfo_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='likePost',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.Post'),
        ),
    ]
